version: '3'
services: 
  tradebotapi:
    image: tradebotapi
    ports: 
      - "5656:5656"
    volumes: 
      - ./tradebotapi/config:/tradebotapi/config
    depends_on:
      - mongo
      - kafka
  tradebotstore:
    image: tradebotstore
    volumes: 
      - ./tradebotstore/config:/tradebotstore/config
    depends_on:
      - mongo
  tradebot:
    image: tradebot
    volumes:
      - ./tradebot/config:/tradebot/config
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.109
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - zookeeper
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
volumes: 
  mongo-data: