version: '3'
services: 
  tradebotapi:
    image: tradebotapi
    ports: 
      - "5656:5656"
    volumes: 
      - ./tradebotapi/config:/tradebotapi/dist/config
    depends_on:
      - mongo
  tradebotstore:
    image: tradebotstore
    volumes: 
      - ./tradebotstore/config:/tradebotstore/dist/config
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
volumes: 
  mongo-data: