apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  namespace: kafka
spec:
  selector:
    app: kafka-zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: client
    protocol: TCP
  sessionAffinity: None
  type: ClusterIP
