apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka01
spec:
  selector:
    app: kafka01
  ports:
  - port: 9092
    targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka01
spec:
  selector:
    matchLabels:
      app: kafka01
  template:
    metadata:
      labels:
        app: kafka01
    spec:
      containers:
      - name: kafka01
        image: wurstmeister/kafka
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9092
        env:
          - name: 'KAFKA_ZOOKEEPER_CONNECT'
            value: 'zookeeper:2181'
          - name: 'KAFKA_ADVERTISED_HOST_NAME'
            value: 'kafka01'
